# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('image', models.URLField(verbose_name='image')),
                ('description', models.TextField(verbose_name='ship description')),
                ('fabrication_date', models.DateTimeField(verbose_name='fabrication date')),
                ('hp', models.CharField(max_length=10, verbose_name='horse power')),
                ('power', models.CharField(max_length=5, verbose_name='power')),
                ('color', models.CharField(max_length=10, verbose_name='color')),
                ('detection', models.BooleanField(default=False, verbose_name='enable detection')),
                ('boost', models.BooleanField(default=False, verbose_name='insterestelar turbo boost')),
                ('passengers', models.IntegerField(default=3, verbose_name='number of passengers')),
                ('reservation_date', models.DateTimeField(blank=True, null=True, verbose_name='reservation date')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
    ]
