# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='ship',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='reservation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reservation date'),
        ),
    ]
